tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: docker-login
    command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - name: Install required linux packages
    command: sudo apt-get install gettext-base -y

vscode:
  extensions:
    - 42Crunch.vscode-openapi
