tasks:
  - name: workspace-init
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      # Download awscli zip
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      # Initialize python packages
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt
      # Initialize npm packages
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i
      cd $THEIA_WORKSPACE_ROOT
    command: sudo /workspace/aws/install && cd $THEIA_WORKSPACE_ROOT
  - name: docker-login
    command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - name: install-linux-packages
    command: sudo apt-get install gettext-base -y
  - name: add-ssh-key
    command: echo -n "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa && chmod 0400 ~/.ssh/id_rsa

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker

ports:
  - name: frontend
    port: 3000
    onOpen: ignore
    visibility: public
  - name: backend
    port: 4567
    onOpen: ignore
    visibility: public

gitConfig:
  user.email: "16061454+vlgermanov@users.noreply.github.com"
  user.name: "Vladimir Germanov"
